### ISSUE TITLE
Help with translations

### ISSUE THREAD

**Issue by bielribeiro18** [tspivey/yugioh-game#151]
Hello dear admins of yu-gi-oh Game.In recent days I noticed that the game is being translated into Portuguese, my native language.I would like to contribute with the translations, how can I do this?

**Comment by Timtam** [comment]
Ok, so the first and bigger problem is that the latest portuguese card database we were able to find on the net is pretty damn old. Maybe you are more lucky than we are and find a more up-to-date one.
When it comes to translating this mud itself, its pretty simple. Just clone the repository, install everything using pip install -r requirements.txt and run ./update.sh pt. this will extract all strings used by the mud itself into the locale/pt/LC_MESSAGES/game.po file. Thats the file you can simply translate, just like you do with gettext() based translations.
The last step would be to translate the help files. Just check out the help folder within locale/en/, copy the whole folder over to locale/pt/ and change the texts within the help files to portuguese.

**Comment by Timtam** [comment]
considered closed
