### ISSUE TITLE
Superheavy Samurai Synchro bug

### ISSUE THREAD

**Issue by Tens00n** [tspivey/yugioh-game#160]
It would appear that Superheavy Samurai synchro monsters do not register as such to the archetype's support/monster cards.  
Cards that only work on superheavy monsters do not work on the superheavy synchro monsters and the superheavy effect monsters that allow you to instantly make a superheavy synchro monster, such as Battleball for example, do not activate as they are supposed to.  The effect monster's behave  as if they do not register that you have a superheavy synchro monster in your extra deck.

**Comment by Timtam** [comment]
You are right, I encountered that bug myself several times already, but this is a card script related bug and nothing we could do something about. I'd recommend to post your issue to the issues within the ygopro-scripts repository instead.

**Comment by tspivey** [comment]
This is a database error. The setcodes don't match what the scripts expect.
I think I fixed it.
