### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by tspivey** [tspivey/yugioh-game#19]
Sometimes when logging in, it's useful to see the chat history.

We should add a command, chat history, to see the last 50 messages.

Problem: soundpacks would play the chat sound for each message. One possible solution is to put a change the message format slightly, for example:
    Tsp: testing (1m)

**Comment by Timtam** [comment]
another solution would be to add a start and end text sp's can trigger to disable channel parsing for that moment.
example:
Chat history:
Toni chats: test (1m)
tsp chats: test worked all fine (1m)
History ends.

**Comment by Timtam** [comment]
added in #97
