### ISSUE TITLE
When using deck edit, decks are created without warning

### ISSUE THREAD

**Issue by tspivey** [tspivey/yugioh-game#2]
When using `deck edit`, decks are created without warning.
This leads to the following situation:
1. I edit a deck and add some cards.
2. I edit that deck again, but typo the name. It doesn't say loading existing deck, but bases the new deck off the deck I'm currently using, which is the first one I edited.
The lack of message is easy to miss.
3. Duel with the new deck, everything seems fine.
4. Later, reload the deck. The changes seem to be lost.

Solutions:
1. Disallow deck edit from creating new decks, because we already have deck new.
2. Explicitly tell the user that a new deck is being created.

**Comment by Timtam** [comment]
deck edit informs the player about newly created decks now.
