### ISSUE TITLE
people waiting in a match are listed as in between match duels

### ISSUE THREAD

**Issue by Timtam** [tspivey/yugioh-game#207]
using who will list people who just opened a match room as in between two match duels.

**Comment by NicklasTegner** [comment]
Unless I'm missunderstanding the problem here, I think this issue has been resolved. When I start a match room and look with who I get


* Nicklasmchd (preparing to duel)
* Nicklasmchd2 (preparing to duel)

which is technically correct

**Comment by Timtam** [comment]
You're right, seems to be solved right now. Closed for now.
