### ISSUE TITLE
add a LICENSE file to allow derivative work

### ISSUE THREAD

**Issue by melvinzhang** [tspivey/yugioh-game#223]
Thanks for writing a Python wrapper for ygopro-core! It is extremely helpful for me as I'm trying to build a search-based AI on top of ygopro-core in Python. https://github.com/melvinzhang/yugioh-ai is my fork of this repo with AI-specific changes.

I realized there isn't a LICENSE file in this repository to indicate that others can modify your work. Would you be willing to provide this repository under an open source license? https://choosealicense.com/ has a list of possible options.

**Comment by tspivey** [comment]
Fixed in c7185f99110a22fb4d18a0c90bf8b695d32a6259.
