### ISSUE TITLE
How it works ?

### ISSUE THREAD

**Issue by egycno** [tspivey/yugioh-game#228]
How it works?
Where is the card script functions file located in this project?
Can it be used in all versions of ygopro, especially ygopro 2, and if so what files can be replaced from ygopro and ygopro 2 files with these Python files in this project?

**Comment by Timtam** [comment]
This project makes full use of YGOPro/YGOPro2, including all of its scripts. We do patch the core a bit to fully integrate it into this project, but all the card scripts are not written by us, but by the YGOPro developer community. Also, no parts of our project can be integrated into YGOPro/other projects. Its the other way around.

**Comment by egycno** [comment]
Thank you .
