### ISSUE TITLE
Counting cards in the deck manager

### ISSUE THREAD

**Issue by blindndangerous** [tspivey/yugioh-game#46]
Instead of the deck manager listing cards like this:
1. Card 1
2. card 1.
3. Card 1.
It would save space and make it faster to scroll if it did this:
1. card 1 x3

**Comment by blindndangerous** [comment]
This issue has been added in the next commit.

**Comment by Timtam** [comment]
done here: 16efa1f366a729cb4b2def91d74b608a52132745
