### ISSUE TITLE
Internal autocompletion

### ISSUE THREAD

**Issue by blindndangerous** [tspivey/yugioh-game#47]
Instead of having to make sure that you type in the entire name for player names, could the game do an internal completion so you could do tell blind instead of tell blindndangerous.  This would help with those who don't have autocompletion in their clients.  Could work for tells and duel accepts.

**Comment by Timtam** [comment]
added in 636d7eb15e69042c2cda5f2da7cf0fbb1a5565b5

**Comment by Timtam** [comment]
@tspivey: close please
