### ISSUE TITLE
different summoning types?

### ISSUE THREAD

**Issue by zironion** [tspivey/yugioh-game#63]
I'd like to see tuner summonings, syncro summonings, dark syncro, and whatever else there is for that.
the game currently doesn't explain that.
take the train archetype it relies heavily on syncro summoning. i'd like to see it announce that.

**Comment by Timtam** [comment]
trains rely on xyz summoning, but other than that won't it be possible.
Reason:
The game doesn't inform us whenever it executes a synchro/xyz/fusion/pendulum/link summon in detail, it only tells us whenever it summons a monster specially, and even though we can check if that monster comes from the extra deck, we don't know if it really was a synchro/xyz/whatever summon, it can simply be a special summon by some effect or something and per definition not a synchro/xyz/whatever summon. The game doesn't handle those things differently.
@tspivey: close please. thanks.
