### ISSUE TITLE
cards with multiple effects

### ISSUE THREAD

**Issue by Timtam** [tspivey/yugioh-game#65]
So there are some great problems we currently have with cards which have multiple effects.
First of all, the idle activation.
We manually check if a card has one effect and offer v to activate it. then we check if the card has exactly two effects, and if yes, we make v2 possible. Thats were the problems come in, because some cards can have even more effects at the moment, making only v an option, but ignore v2, v3, v4, ... totally.
Thats why we should make idle effect activation flexible, which shouldn't be a big problem.

Second problem is an even bigger one. The chain effect activation. Some cards offer multiple effects in here too, showing a list like the following:
s6: Noble knights of round table
s6: noble knights of round table
s6: noble knights of round table

The player can't even really decide, even though the mud interface realizes that there are more than just one effect he can use, since the command to use it is the same, he will always just use the first effect.
i'm not sure how to solve this problem, please give some ideas how the alternative commands should be called?

Last problem, chains with only one card don't show the chaining option, but only the yes-no question, if you want to activate this card. they ignore the appearance of multiple effects completely. i'm not sure if this is ygopro-core related, but if you say yes, it will always only use the first effect, instead of asking you which one you want to use.
Maybe we can solve this by splitting the effects up and showing them like a usual chain request (see above).

So, please make some noise and send some ideas how the chain reaction commands should be called.

**Comment by tspivey** [comment]
For the first problem, v2 can be removed entirely. Instead, v will show something like:
```
Select effect to activate (1-2, z=back):
```
Which will let me choose which one to activate.

Chains could work a similar way, only showing each spec once, then letting you choose from a menu if there's more than one.

**Comment by Timtam** [comment]
fixed in #66 and #67
