### ISSUE TITLE
Disconnecting all players in a duel

### ISSUE THREAD

**Issue by tspivey** [tspivey/yugioh-game#82]
When all players in a duel disconnect, reconnection no longer works.

Maybe the duel should end in that case.

**Comment by Timtam** [comment]
oh yeah, didn't try that.
Nope, I re-designed it so that all players can easily disconnect and it should be able to continue as soon as all are back. Will take a look into it later.

**Comment by Timtam** [comment]
fixed in 07631b4f2e6e6138d35e856e46a50120110ca447
