### ISSUE TITLE
player calling out attacks?

### ISSUE THREAD

**Issue by zironion** [tspivey/yugioh-game#85]
I'd like  to know how difficult it would be to code in the ability to call out attacks like the anime does?
example: blue-eyes attack white lightning. something like that.

**Comment by Timtam** [comment]
Not happening. We don't have time to invent names for attacks for several thousand monsters. Do it yourself if you like, shouldn't be a bit problem using triggers client-side.

**Comment by zironion** [comment]
it should not be a major problem. isn't there a db out there that has
the files that contain the strings for each and every card? just
having to hook it in?


On 10/11/17, Toni Barth <notifications@github.com> wrote:
> Closed #85.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tspivey/yugioh-game/issues/85#event-1287721632


-- 
Justin Hart

**Comment by Timtam** [comment]
its the default database that contains name, description and effect strings, but no extravagant stuff like attack names, and we're not going to alter databases for things you can do in your sp on your own. much to much overhead for such stuff.

**Comment by zironion** [comment]
it was just a suggestion to make the game more worth while. don't get
your panties up in a knot.
I don't even know how to altered the sp in order to do that. to my
knowledge the game would have to support the pack in  some fashion, or
scripts to be loaded for me to even support it.


On 10/11/17, Toni Barth <notifications@github.com> wrote:
> its the default database that contains name, description and effect strings,
> but no extravagant stuff like attack names, and we're not going to alter
> databases for things you can do in your sp on your own. much to much
> overhead for such stuff.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tspivey/yugioh-game/issues/85#issuecomment-335754151


-- 
Justin Hart

**Comment by Timtam** [comment]
don't think so. simply catch the attack phrases, parse the monster name out of it and if its the correct one, send an additional text line which calls out the attack. simple client-side magic, nothing we need to add server-side.

**Comment by zironion** [comment]
it doesn't have anything to capture given a textual format. I'd have
done that if I had that sort of text to capture.
x monster attacks, nothing to capture. so how do I capture a string
that doesn't exist?
I am finished with this since you don't seem to care about seeing my
point of view, so screw it all. I will not suggest anything anymore on
GitHub.  all my suggestions to the contrary meet with resistance.
this isn't worth doing if I make a suggestion and end up getting
responses that say nobody will do it because you won't make a few
changes.  whoever responds to this just know I find it massively
frustrating to suggest something. anything that requires work, and it
is a fuck all and no we won't do it. if the core, or code can not
support my suggestion then that is all I need to know.
when I get text I can capture from the game that parses out
information, then I can improve my sp. until then the game doesn't do
that.  I'm done. please don't reply. I don't care anymore. I am  to
frustrated to care about this topic. I mean not to offend anyone but
for real....



On 10/11/17, Toni Barth <notifications@github.com> wrote:
> don't think so. simply catch the attack phrases, parse the monster name out
> of it and if its the correct one, send an additional text line which calls
> out the attack. simple client-side magic, nothing we need to add
> server-side.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tspivey/yugioh-game/issues/85#issuecomment-335756517


-- 
Justin Hart

**Comment by Timtam** [comment]
Well, I don't know your problem here, but i'm not dedicated to be your personal problem solver, so yeah.
Just fyi: We got messages like "Toni attacks with Blue-yed white dragon" or "Toni attacks m1 (facedown-defense) with blue-eyed white dragon". So why do you insist that we don't have any parseable content?
Simply parse this text (it says which monster attacks there) and react on the monster name to print an additional message which calls the attack name, or gag the original one additionally if you like.
I'd recomment to read the text we got in game first before submitting suggestions. There isn't anything wrong about doing so, but you shouldn't be upset if we decline those because it doesn't make sense to add them server-side, if you can do it more easily client-side.
And think about yourself before complaining. Thanks for reading. I guess this should be finished now.
